Let parental header included by summary.
misohena/gcal pull request #3
Opened 2021-01-28 08:54 UTC by ROCKTAKEY

org-modeで予定やタスクを管理する場合、親ヘッダも含めて意味を持つことがよくあると思います。
```org-mode
* 本の名前
** 1章
*** 1節
```
このような場合、親ヘッダも含めてgoogle Calendarに予定登録できるといいなあと思い、機能を追加してみました。

2021-01-29 00:32 UTC, misohena requested changes
PRありがとうございます。確かに「1節」だけでは訳が分かりませんね。
私の場合「Inbox/○○をする」なのでむしろ入っていない方が良いのでカスタマイズできるのは嬉しいです。
ファイル毎の切り替えやさらなるカスタマイズ性(任意の関数を設定？)が必要になるケースもありそうですが、ひとまずこれで良いと思います。

いくつか気になるところをがあったのでコメントを入れました。修正可能でしょうか。お手数ならマージしてこちらで修正することも可能です。

2021-01-29 00:32 UTC, misohena commented on gcal-org.el
> +  :type '(choice number (const t)))
おそらく :type 'string ?

2021-01-29 00:32 UTC, misohena commented on gcal-org.el
> +                    (list (org-get-heading t t))))
元のコードが (substring-no-properties (org-get-heading t t)) となっているのはおそらくorg-get-headingが返す文字列にテキストプロパティが付いているのを嫌ったのだと思います。あっても問題ないのかもしれませんが、org-get-outline-pathが返す文字列には付いていないようですし、念のためsubstring-no-propertiesを挟んでテキストプロパティを消してもらえないでしょうか。

一瞬(org-get-outline-path t) (WITH-SELF=t)でいいのかなと思ったのですが、priority([#A]等)が消えてしまうのでダメそうですね…。私はあまりpriorityは使っていませんし、本当は消えた方が良いのかもしれませんけれど……

2021-01-29 00:32 UTC, misohena commented on gcal-org.el
> +                    path)
gcal-org-include-parents-header-maximum が nil のときは0を指定したのと同じになって欲しい気がします。
いや、変数を定義していない人はdefcustomでtになるから不要でしょうか？
nilもtも同じになるのはどうなのかなと思ったもので。

あ、あとnumberpではなくintegerpかもです。となるとdefcustomの方もnumberではなくintegerですね。

2021-01-29 04:18 UTC, ROCKTAKEY commented on gcal-org.el
> +  :type '(choice number (const t)))
失礼しました。一つ上と混ざってしまっていますね。

2021-01-29 04:18 UTC, ROCKTAKEY commented on gcal-org.el
> +  :type '(choice number (const t)))
```suggestion
  :type 'string
```

2021-01-29 04:24 UTC, ROCKTAKEY commented on gcal-org.el
> +                    (list (org-get-heading t t))))
確かにこれはWITH-SELF=tのがよい気はしますね、priorityも消えるべきだと思います。
とりあえずsubstring-no-propertiesを追加しておきます。
```suggestion
                    (list (substring-no-properties (org-get-heading t t)))))
```

2021-01-29 04:33 UTC, ROCKTAKEY commented on gcal-org.el
> +                    path)
これは正直難しいところで、私は無限大を想定して `t` を導入したのですよね。そして、defcustomのtypeで整数(integerに直しておきます)もしくは `t` と指定しているので、nilになることを考える必要があるのか、という問題になると思います。
というのも、typeで指定したもの以外を考えるとキリがないのですよね(それこそ浮動小数とか、シンボルならどうなのだとか)

2021-01-29 04:40 UTC, ROCKTAKEY commented
それともうひとつ、後からきがついたのですが、pull操作については一切考慮していませんでした。pullするときに名前に変更があると、親ヘッダを含めてヘッダに書き込まれるかもしれないです。

2021-01-29 04:51 UTC, misohena commented on gcal-org.el
> +                    (list (org-get-heading t t))))
Googleカレンダー側にpriorityがあれば堂々と消せるのですがなさそう(タスクではなく予定ですししょうが無いですが)なので迷うんですよね。
とりあえずこれで。

2021-01-29 04:57 UTC, misohena commented on gcal-org.el
> +                    path)
:typeはbooleanではなく(const t)ですもんね(つまりmaximumにする、という意味か)。確かにnilはやりすぎですね。すみません。'infiniteみたいなシンボルでも良さそうですが、うーん、別にどっちでもいいですね。取り消します。

2021-01-29 05:05 UTC, misohena commented
> それともうひとつ、後から気がついたのですが、pull操作については一切考慮していませんでした。pullするときに名前に変更があると、親ヘッダを含めてヘッダに書き込まれるかもしれないです。

確かに！

2021-01-29 05:24 UTC, ROCKTAKEY commented
一番単純なのは、separatorで分解して最後を取り出すことかなあと思います。
ただ、ヘッダにもseparatorと同じ文字列が存在するときにややこしいことになるのと、separatorが変更されたときには分けようがないことがあります(正直なところ、後者はどうしようもないと思いますが)。

2021-01-29 05:36 UTC, misohena commented
/はよく使っているので単純にseparatorで分割するわけにはいかなそうですよね。

まずgcal-org-include-parents-header-maximumの値に応じて動作を変えるべきかもしれません。少なくとも0のときにこれまで通りの動作を保証したいところです。先頭から指定された個数分のseparatorの後、というわけにも行かなそうですね……(親要素のヘッドラインに/が入っている可能性が)

取り込み先エントリーのpathを取得してマッチングするという方法も考えましたが、push後に移動してしまっているかもしれないので確実ではなさそう。

parentsとselfの間に特別な記号を挿入すれば、そしてその記号を目的以外で使わないことを前提条件にすれば可能でしょうか。aaa/bbb::ccc

Googleカレンダー側に親のパス(aaa/bbb)をどこか別のプロパティに突っ込めればいいのかもしれませんが……

ちょっとじっくり考えたいところですね。

2021-01-29 06:16 UTC, ROCKTAKEY commented
>parentsとselfの間に特別な記号を挿入すれば、そしてその記号を目的以外で使わないことを前提条件にすれば可能でしょうか。aaa/bbb::ccc

これはわりとありかもしれません。問題点としては、使わない文字列となるとほぼ必然的に2文字以上になってしまうところ、でしょうか。表示領域的な意味では2文字とってしまうのは痛手ですよね....

>Googleカレンダー側に親のパス(aaa/bbb)をどこか別のプロパティに突っ込めればいいのかもしれませんが……

一番単純なのは、descriptionの末尾に"gcal-path: aaa/bbb"みたいな形で挿入、でしょうか。
gcal経由で登録されたものでない場合は親が存在しないことを踏まえ、親が存在する場合のみ親のpathを挿入する、という形をとればよいのではないでしょうか。こうしておけば、gcal経由でない予定のdescriptionがgcalに汚されてしまうことはないので。

あとこれは本筋とは関係ないですが、別の機能として、descriptionの部分をアウトラインの本文に読み込むのはありかも、と思いました。

2021-01-29 06:56 UTC, ROCKTAKEY commented
>ファイル毎の切り替えやさらなるカスタマイズ性(頭の階層を取り除くとか任意の関数を設定とか？)が必要になるケースもありそうですが、ひとまずこれはこれで良いと思います。

あっあとちなみに、ファイルごとの切り替えに関しては、Emacs標準のlocal variable機能(任意のファイルの先頭や末尾で変数を設定できる)があるので問題ないかなあと思いました。

2021-01-29 06:58 UTC, misohena commented
一番簡単なのはmaximumを0以外に設定したらヘッダー内にseparatorを使用しない約束に同意したと見なす方法ですねw

> 問題点としては、使わない文字列となるとほぼ必然的に2文字以上になってしまうところ、でしょうか。表示領域的な意味では2文字とってしまうのは痛手ですよね....

カレンダー内での文字数は結構貴重ですもんね。結局確実な文字列を確保するのは無理ですし、見た目もちょっと汚い。
(ex:日記/1/4の出来事::::1/8ずつのご飯)

> descriptionの末尾に"gcal-path: aaa/bbb"みたいな形で挿入

調べたところGoogleカレンダーにはExtended Propertiesという仕組みがあるようです。
https://developers.google.com/calendar/extended-properties
そこにpathInOrg(orgPath?)のようなプロパティを追加すれば何とかなるかもしれません。

取りこんだsummaryの先頭部分がこのプロパティと一致したらその部分を除去するわけですね。
summaryの先頭部分をGoogleカレンダー側で変更してしまった場合は仕方ないので全体をヘッダーとするしかなさそう(変更されたパスへ移動する！？w)。
もちろん不要ならこのプロパティは追加しない方向で。

これをやるにはoeventは:summaryとは別に:pathを持たせた方が良さそう。

> descriptionの部分をアウトラインの本文に読み込む

一つのoeventを一つのタイムスタンプに対応させてしまっているので厳密にやろうとすると大変かもしれませんね。少なくとも新規の予定を取りこむときはSCHEDULEDと共にdescriptionを反映させることはできそう。Googleカレンダーでorgが編集できるのは便利そうではあります。

2021-01-29 07:20 UTC, ROCKTAKEY commented
>一番簡単なのはmaximumを0以外に設定したらヘッダー内にseparatorを使用しない約束に同意したと見なす方法ですねw

separatorもカスタマイズ可能にしていますし、使う人が自分で決めてもらえるならそれはそれでありかもしれないですw

>調べたところGoogleカレンダーにはExtended Propertiesという仕組みがあるようです。
https://developers.google.com/calendar/extended-properties
そこにpathInOrg(orgPath?)のようなプロパティを追加すれば何とかなるかもしれません。

なるほど、拡張でプロパティを持てるならそのほうがよいですね。

>取りこんだsummaryの先頭部分がこのプロパティと一致したらその部分を除去するわけですね。
summaryの先頭部分をGoogleカレンダー側で変更してしまった場合は仕方ないので全体をヘッダーとするしかなさそう(変更されたパスへ移動する！？w)。

これが起きたときの処理がかなり難しいですね。できるなら変更されたパスへ移動したいところですが、そもそも親ヘッダの中身を変更したのか親そのものを挿げ替えたのかが分からないのと、親ヘッダの中身を変更したとみなす場合は他の予定にも影響を与えてしまう(つまりpullしたのにdiffが残る)ということになっています。
なので、もしやるとすれば、常に親を新規作成するのが妥当かなあと思いますが、それでも結局separatorでsummaryを分割しないといけない問題は残るので、おっしゃるとおり全体をヘッダにするのがよさそうな感じがします。

あと、separatorの変更に対応するために、プロパティにseparatorの情報も含めて、pathInOrgにはリストで保存するのがよいかなあと思っています。(つまり`org-get-outline-path`の返り値をそのままprincとかで吐いて保存し、使うときは`read`で読んだあと、旧セパレータの情報でstring-joinしてから比較する)

>一つのoeventを一つのタイムスタンプに対応させてしまっているので厳密にやろうとすると大変かもしれませんね。少なくとも新規の予定を取りこむときはSCHEDULEDと共にdescriptionを反映させることはできそう。Googleカレンダーでorgが編集できるのは便利そうではあります。

たしかに、そうでした。予定に説明つけることもそこそこにあるので、pullには対応できなくてもpushくらいはできたら便利だと思います。

2021-01-29 07:24 UTC, ROCKTAKEY commented
ふと思ったんですが、そもそも現状として、複数のタイムスタンプのついているヘッダに対応するcalendar上の予定が、1つだけ変更されている場合はどうしているのでしょうか。

2021-01-29 12:37 UTC, misohena commented
> あと、separatorの変更に対応するために、プロパティにseparatorの情報も含めて、pathInOrgにはリストで保存するのがよいかなあと思っています。(つまり`org-get-outline-path`の返り値をそのままprincとかで吐いて保存し、使うときは`read`で読んだあと、旧セパレータの情報でstring-joinしてから比較する)

「pathをどうやって文字列にしたらいいだろうseparatorのエスケープが必要かな面倒だな」と思っていましたがリストをprinc等で変換するのは良さそうですね。そうなると確かに出力時のsepratorも必要ですね。

> ふと思ったんですが、そもそも現状として、複数のタイムスタンプのついているヘッダには複数の予定がカレンダーで生成されますが、pullしたときにそのうちの1つだけが変更されている場合はどうしているのでしょうか。

その変更が取りこまれます。ただし、y/n選択肢が出るのでnを押したら取りこみません。その後pushすると、そのヘッドラインが他の予定のsummaryへ反映されます。

同じエントリーに紐付く複数の予定のsummaryをそれぞれ別に変更した場合、何らかの順番(おそらく日時順)で取り込み処理が連続で走ります。yを押し続けたらおそらく最も遅い日時のsummaryがヘッドラインに残るのではないかと思います。

pullの動作は@todoの所を見てもあまりよく実装されていないみたいです。

本当はDEADLINEの予定を消したらDEADLINEのタイムスタンプだけが消えて欲しい気もしますが現状はそのようになっていません。エントリー全体を消すかどうかy/nで聞いてきます。

ちなみに白状しますと、私はOrg→Googleカレンダーは毎日使いますがGoogleカレンダー→Orgはめったにやりません。Googleカレンダー上にOrg専用カレンダーを作っているのですが、そこにGoogleカレンダー側から予定を追加したり、修正することがほとんどありません。何となくバグでデフォルトのカレンダーが全部吹っ飛んだらやだなとかこれまでの予定が沢山あると重くなりそうだな等と思いカレンダーを分けたのですが、そうするとスマホ等からは何となくデフォルトのカレンダーに予定を入れてしまうので自動的にOrgに取りこまれません。必要なら手動でorgファイルに入力していたりします。そろそろ一緒にしてしまっても良いのかなという気もするのですが……。TODOをarchiveするとカレンダーからも消す運用をしているので、その兼ね合いもあるかもしれません。過去の予定をGoogleカレンダーに残したい場合は一緒には出来ません。過去の予定をorg側でずっとアクティブなまま残しているとそのうちかなり重くなると思うんですよね。同期する期間を限定すれば大丈夫かもしれませんが。

2021-01-29 13:33 UTC, ROCKTAKEY commented
>「pathをどうやって文字列にしたらいいだろうseparatorのエスケープが必要かな面倒だな」と思っていましたがリストをprinc等で変換するのは良さそうですね。そうなると確かに出力時のsepratorも必要ですね。

とりあえずこの方針で実装してみます！google apiに全く詳しくないのでできるか怪しいですが

>その変更が取りこまれます。ただし、y/n選択肢が出るのでnを押したら取りこみません。その後pushすると、そのヘッドラインが他の予定のsummaryへ反映されます。
>同じエントリーに紐付く複数の予定のsummaryをそれぞれ別に変更した場合、何らかの順番(おそらく日時順)で取り込み処理が連続で走ります。yを押し続けたらおそらく最も遅い日時のsummaryがヘッドラインに残るのではないかと思います。

なるほど、そうなのですね。それならば、descriptionも同様の動作で実装すれば仕様の一貫性もありますし問題ない気がします。

>本当はDEADLINEの予定を消したらDEADLINEのタイムスタンプだけが消えて欲しい気もしますが現状はそのようになっていません。エントリー全体を消すかどうかy/nで聞いてきます。

自分は #4 を使ってSCHEDULEとDEADLINEを消してしまっているのであまり気になりませんでしたが、たしかにそのほうが自然ですね。削除対象の分岐をしないといけないのが大変ではありますが....

>ちなみに白状しますと

実は私もpushしか使ってないのですよね....

>過去の予定をorg側でずっとアクティブなまま残しているとそのうち同期がかなり重くなると思うんですよね。同期する期間を限定すれば大丈夫かもしれませんが。

たしかにこれはそうかもしれないですね....いっそのことpush/pullの関数にoptional引数を追加して、デフォルトでは未来の予定のみを対象にする、とかよいかも

2021-01-29 15:00 UTC, misohena commented
> とりあえずこの方針で実装してみます！google apiに全く詳しくないのでできるか怪しいですが
ありがとうございます！
私もこのプロジェクトで学んだようなものなのでよく分かっているわけではありませんが、疑問な(不審な?)点がありましたらいつでもお声がけください。

私もこれを機に暇なときに少しいじってみようかなとも思います。

2021-01-30 12:51 UTC, ROCKTAKEY commented
>とりあえずこの方針で実装してみます！google apiに全く詳しくないのでできるか怪しいですが

一応完成致しました！少なくとも私の手元では、今commitしたもので動いています。
Extended Propertiesを追加したために変更が多くなっていますが、お時間のあるときに確認して頂けると嬉しいです。

2021-01-30 17:57 UTC, misohena commented
お疲れ様です。コードの方拝見しました。元々のしくみ自体をかなり忘れてますね私。思ったよりも読むのに苦労していますw。Extended Propertiesは元々一部で使っていたのですね。全く記憶にありませんでした(今でも何に必要だったのかよく思い出せません)。

それで読んでいてoeventの構造について少し気になるところがあったのでご意見を伺いたいのですがよろしいでしょうか。

今回の変更ではoeventの:summaryにテキスト化した親のパスも含めてしまう(gcal-org-make-oevent-summaryの結果を:summaryに入れる)形になっていますよね？　ヘッドラインテキストそのもの(org-get-headingの値)だけ入れるのではだめでしょうか。:summaryに:path(の一部)が含まれているのが何だか無駄な気がしたもので。

gcal-org-pull--entry-mod内で(gcal-org-pull-merge-property "headline" ...)を呼んでいる部分の変更を見て違和感を感じまして、過度に複雑になっていると言いますか……。元から:summaryにパスが含まれていなければこの変更はしなくて良いと思います。(;;update objectのところでnew-oeを参照しているのも厳密にはあまり良くない気がするのですが実質的には問題が起こらなそう……)

oeventの:summaryには本来のヘッドラインテキストだけ入れて、Googleカレンダーとの変換関数(gcal-oevent-to-gevent と gcal-oevent-from-gevent)でsummaryを変換した方がわかりやすい気がします。

そう考えると本来は:summaryは:headlineとでもすべきだったのかもしれません。

それと:pathを持たせた方が良さそうと言った手前申し訳ないのですが、本当に必要なのは:path, :separator, :header-maximumではなく:summary-prefixだったのではないでしょうか。厳密なフルパスをGoogleカレンダーのプロパティに登録する必要は無く、summaryの先頭にヘッドラインテキスト以外の何を付加したかを持たせれば十分ではないでしょうか。

実質的に何か問題が起きるかというと大きなものは思いつかないのですが、例えばoeventに:path(フルパス)を持たせてしまうとエントリーを別のパスに移動しただけで不必要に同期が走ってしまう可能性があります。header-maximumが0(または階層の深さに対して十分小さい)時、エントリーを別の場所に移動してもsummaryは変わらずGoogleカレンダーの更新は必要ないはずです。しかし:pathにフルパスが入っていると、push時にバッファから収集した:pathとキャッシュから得た:pathが食い違い、変更があったと見なされGoogleカレンダーに対して更新をかけてしまいます。oeventの比較関数に手を入れる方法もありますが、:summary-prefixだけ持たせる形にすれば現状の(equal old-oe new-oe)による比較でも大丈夫です。同様にトップレベルにあるエントリーは:pathが空になるのでいかなる時もsummaryはヘッドラインテキストだけになりますが、header-maximumを変更しただけで変化があったと見なされてしまいます。

まとめると
1. gcal-oevent-summary-prefixを定義する。
2. gcal-org-parse-bufferではsummaryは従来通りにし、summary-prefixを作成する。
3. gcal-org-pull--entry-modは変更の必要なし。
4. gcal-oevent-to-geventでは出力のsummaryをoeventの:summary-prefix + :summaryに、出力のgcalSummaryPrefixをoeventの:summary-prefixにする。
5. gcal-oevent-from-geventでは出力の:summaryをgeventのsummaryからgeventのgcalSummaryPrefixを除いたものにする(gcal-oevent-make-header-lineのように。あれこのstring-matchは途中にマッチする可能性があるのでは)。出力の:summary-prefixはgeventのgcalSummaryPrefixにする。

ということになります(何か見落としがあったらすみません)。

せっかく書いて頂いて動いているのに気が引けるのですが、いかがでしょうか。
ある意味私の趣味も入っているかもしれないので、いったんマージして私の方で修正した方が良いのかもしれませんが……。
ご意見お聞かせ頂ければ幸いです。

あ、あとgcal-org-header-separatorの:type 'stringの件とnumberpの件が消えてしまっていると思います。

2021-01-30 18:20 UTC, ROCKTAKEY commented
私も全面的に同意します。確かによく考えれば、geventとoeventの変換で気を付ければsummaryにprefixは必要ないですし、二重管理なのは気持ち悪いですもんね。。直してみます

>あれこのstring-matchは途中にマッチする可能性があるのでは

`(eq 0)`をつけるつもりだったのですがすっかり忘れてました。。。すみません

>あ、あとgcal-org-header-separatorの:type 'stringの件とnumberpの件が消えてしまっていると思います。

これもたぶんミスですね。。。コードの管理がなってなくてすみません。。。

2021-01-30 20:10 UTC, ROCKTAKEY commented
summary-prefixを使った形式に変更致しましたので、是非ご確認下さい！
手元でテストした限りではよく動いています。

2021-01-31 01:16 UTC, misohena requested changes
修正ありがとうございます！
大分すっきりしましたね。ほぼ問題ないと思います。
summary-prefixの取り扱いで少し気になったところがありましたのでコメントを入れました。

2021-01-31 01:16 UTC, misohena commented on gcal-org.el
> +              ,@(when summary-prefix `((gcalSummaryPrefix . ,summary-prefix)))))))
summary-prefixがnilの時だけでなく空文字列の時もプロパティを出力しない方が良さそう。

2021-01-31 01:16 UTC, misohena commented on gcal-org.el
> +         summary)
Googleカレンダーから新規で予定を追加したとき、summary-prefixはnilになり得ます。
試したところ string-match: Wrong type argument: stringp, nil となりました。

ちなみにeq 0でも良いのですが正規表現の頭に \\` を付けると文字列先頭とマッチします。
substringをかけてから比較してもいいのですが……あ、今探したらstring-prefix-pという関数がsubr.elに見つかりました。
DL:の除去もこれでやれば良かったですね。関係ないですがDL:は〆:とかにしたい人もいるかもしれないのでそのうち修正します。ハードコードされてて恥ずかしい……。
string-remove-prefixなんて関数も見つけましたがこちらはsubr-x.elですね。

2021-01-31 01:16 UTC, misohena commented on gcal-org.el
> +                                gcal-org-include-parents-header-maximum))
gcal-org-include-parents-header-maximumが0のときは(org-get-outline-path)(やgcal-org-make-summary-prefix自体)を呼び出す必要はないのではないかと前から気になっています。
たいていの場合パフォーマンスは無視できる違いしか無いと思いますが、org-get-outline-pathはバッファを遡って探していくので文書によっては遅くなるかなと。
心配しすぎかもしれませんがどうでしょう。

2021-01-31 07:05 UTC, ROCKTAKEY commented on gcal-org.el
> +              ,@(when summary-prefix `((gcalSummaryPrefix . ,summary-prefix)))))))
たしかにそうですね。summaryがnilになる場合と空文字列になる場合の両方があるのが絶妙に嫌ですね。。。

2021-01-31 07:16 UTC, ROCKTAKEY commented on gcal-org.el
> +         summary)
>Googleカレンダーから新規で予定を追加したとき、summary-prefixはnilになり得ます。
試したところ string-match: Wrong type argument: stringp, nil となりました。

了解です。from-geventのところでnilの場合を排除すればよさそうですかね。。

>ちなみにeq 0でも良いのですが正規表現の頭に \` を付けると文字列先頭とマッチします。
substringをかけてから比較してもいいのですが……あ、今探したらstring-prefix-pという関数がsubr.elに見つかりました。
DL:の除去もこれでやれば良かったですね。関係ないですがDL:は〆:とかにしたい人もいるかもしれないのでそのうち修正します。ハードコードされてて恥ずかしい……。
string-remove-prefixなんて関数も見つけましたがこちらはsubr-x.elですね。

総括すると、string-remove-prefixを使えばよいでしょうか。

消してしまうので関係のないことですが、eq 0を使っているのには一応理由がありまして、 `regexp-quote` が"\\|"を含む正規表現を吐く場合(たとえば`aaa\\|bbb`。まあquoteするだけなのでまずないと思いますが)、 優先順位の関係で単純にconcatでバッククオートを 先頭に繋ぐと`aaa`のほうにのみ文字列先頭マッチの効力が働き、文中の `bbb`にまでマッチしてしまうのですよね。そのため、念を入れると `\\(\\)`で囲うこととなり、それでは冗長だからeq 0のがよいかなあと思ったのです。

2021-01-31 07:18 UTC, ROCKTAKEY commented on gcal-org.el
> +                                gcal-org-include-parents-header-maximum))
たしかにいわれてみればそうですね。。。変更します

2021-01-31 07:32 UTC, ROCKTAKEY commented
修正致しました！
summary-prefixに関しては、そもそもnilになること自体が問題だと思ったので、常に文字列になるように修正しました。

2021-01-31 08:01 UTC, misohena commented on gcal-org.el
> +         summary)
> 総括すると、string-remove-prefixを使えばよいでしょうか。

subr-x.elの関数を気軽に使って良いのかなとかよく分からなくて……。clがダメとか聞きますし、Emacs Lispの流儀がよく分からなくていつも困っているんです。
いや、すみません。使っちゃって大丈夫だと思います。

> 消してしまうので関係のないことですが、eq 0を使っているのには一応理由がありまして、 regexp-quote が"\|"を含む正規表現を吐く場合(たとえばaaa\\|bbb。まあquoteするだけなのでまずないと思いますが)、 優先順位の関係で単純にconcatでバッククオートを 先頭に繋ぐとaaaのほうにのみ文字列先頭マッチの効力が働き、文中の bbbにまでマッチしてしまうのですよね。そのため、念を入れると \\(\\)で囲うこととなり、それでは冗長だからeq 0のがよいかなあと思ったのです。

なるほど失礼いたしました。それは確かにハマりそうなやつですね。今は良くても将来の改良でやらかすのもありそう。
私は正規表現エンジンをわざわざ起動するほどのことかなとつい思ってしまうたちでして(実際に中がどうなっているのか知りませんが)、今回はそのものズバリな関数があるのでそちらを使うのが良いですね。

2021-01-31 08:18 UTC, misohena requested changes
修正ありがとうございます。少しだけ問題が。これで最後だと思います。

2021-01-31 08:18 UTC, misohena commented on gcal-org.el
> +              ,@(when (string-empty-p summary-prefix)
(not (string-empty-p ではないかと思います。良くやります。

2021-01-31 08:18 UTC, misohena commented on gcal-org.el
> +           (string-remove-prefix summary-prefix summary)
この時点でsummary-prefixがnilになっている可能性があります。
(string-prefix-pの中身を見るとかろうじて大丈夫なような……いや、ギリギリダメですねprefixが""のとき。いや、どのみちnilを渡すべきでは無いと思いますが)

letでsummary-prefixを作るところで非nilを保証した方が良いと思います。

2021-01-31 09:06 UTC, ROCKTAKEY commented
詰めが甘かったです、すみませんでした。。
また修正致しました！

2021-01-31 10:22 UTC, merged

2021-01-31 10:24 UTC, misohena commented
マージしました！
今回はありがとうございました。
色々修正すべき点が見つかったので私も少し手を入れてみようと思います。

2021-01-31 11:13 UTC, misohena commented on gcal-org.el
> +              ,@(when summary-prefix `((gcalSummaryPrefix . ,summary-prefix)))))))
すいません、これやっぱりまずいので取り消します。

2021-01-31 11:18 UTC, misohena commented
すみません、summary-prefixが空の時にgcalSummaryPrefixを出力しない件ですが、以前空ではなかったのが空になるとGoogleカレンダー上でgcalSummaryPrefixが以前のまま残ってしまう問題があるのでこちらで修正させて頂きました。
657e8ab90ba35f9bee0a33a5768ed0258dd457f2

PATCHメソッドで予定を更新しているのですが、当然ながら存在しないプロパティは更新されないだけで削除されません。空文字列でもgcalSummaryPrefixを設定してしまうのが手っ取り早いのでそのようにしました。お手数をおかけしたのに申し訳ありません。

2021-01-31 11:24 UTC, ROCKTAKEY commented
了解です！
いえいえ、使いやすいのが一番ですので！